### PR TITLE
Add class filtering to modeldoc

### PR DESCRIPTION
**Pull request by mint-thompson**
Various enhancements to the model documentation. The primary focus is on filtering the class list. This list can be filtered to show only Entries, Groups, or Elements. Additionally, a text field is available for filtering based on class name.

### CODE REVIEW

**Comment by kjmahalingam** [comment]
Nice work! Looks good. The only thing I want to check with @cmoesel when he returns is about the introduction of jquery. I think it's fine and it works great, but since this required the introduction of a this new library that I don't believe is used elsewhere in the toolchain, I want to make sure that's something we want to solidify.

**Comment by cmoesel** [comment]
This looks great, @mint-thompson!  I'm fine with the inclusion of jquery -- especially if it's the right tool for the job!

In trying it out, I had one question.  It seems to me that the namespace picker on the upper left doesn't do anything.  Am I missing something?  I'm using FireFox on Mac.

image

**Comment by cmoesel** [comment]
Regarding the issue noted above: based on discussions w/ @mint-thompson, cross-frame javascript does not work well when accessing pages over the file system (instead of via a web server). I tried hosting it on a local web server instead and confirmed that it works as expected!

@markkramerus -- is it OK for the modeldoc to require a web server for full functionality, or do we need it to be 100% functional when loading it from disk as well?

**Comment by markkramerus** [comment]
> @markkramerus -- is it OK for the modeldoc to require a web server for full functionality, or do we need it to be 100% functional when loading it from disk as well?

It's pretty rare to access the IG on a local file system, but it does happen. If we are at a dead end technically, let's go ahead and release this, because it is a big improvement. But we'll also have to document this limitation. If there is a technical solution at hand, let me know how many hours it might take to implement it.

**Comment by mint-thompson** [comment]
941a34f resolves the issue that came up when viewing the modeldoc on a local filesystem. It also resolves some browser compatibility issues.

**Comment by cmoesel** [comment]
Cool!  It works!  I tested w/ FF and Safari on Mac (I don't have Chrome installed, sorry).

I only noticed one minor thing that would be a nice-to-have.  Right now, it starts with the main content (right pane) being the overview of all classes.  When you filter by a namespace, the main content changes to list all the classes in that namespace.  If you then choose "All Namespaces", however, the main content (right pane) does not change (it stays on the last selected namespace).  I expected it to go back to the overview that shows all classes in all namespaces.

Is this an easy fix?

**Comment by mint-thompson** [comment]
> Is this an easy fix?

It is! This is now addressed in commit 75023bf.

**Review by cmoesel — APPROVED** [review]
Perfect.  Thanks!

**Review by kjmahalingam — APPROVED** [review]

**Pull request merged**
