### PR TITLE
Markdown support in descriptions

### PR DESCRIPTION
**Pull request by Abhijay**
This allows for markdown support in descriptions of elements and
namespaces

(Note: this commit still has the original paragraph tags thats cause
extra whitespace in table)

### CODE REVIEW

**Comment by cmoesel** [comment]
MD support looks great.  I noticed one issue that probably is not related to this PR, but... when I click the "All Classes" link in the top left, I expect the bottom left pane to include all classes (every package), but it doesn't.  Is this a known issue?

**Comment by cmoesel** [comment]
If it's an easy fix, go ahead and add it to this PR.  If it's not, then let me know and I'll merge it as-is.

**Comment by Abhijay** [comment]
Believe it or not, this is actually the intended behavior as of: https://github.com/standardhealth/shr-json-javadoc/commit/6b65885af2b0b9cc4982e821de72ff2d28912fd4#diff-168726dbe96b3ce427e7fedce31bb0bcR134

It used to behave as you described, but Mark put in a feature request to omit all top-level elements from that list. I agree that it's not necessarily the most intuitive result, so it might be worth revisiting that conversation separately.

**Comment by cmoesel** [comment]
OK.  It's not what I think I or anyone else would expect, but let's revisit separately.  Merging this is now.

**Pull request merged**
